#' Generates all minimum makespan schedules for a cpm network
#' 
#' @name cpm.all.schedule
#' 
#' @aliases cpm_all_schedule genAllCpmSched 
#' 
#' @param matrix with est,eft, lst, lft for all activities
#' 
#' @description Generates all minimum makespan schedules for a cpm network
#' 
#' @export
#' 
#' @return Matrix with all mininum makespan cpm schedules (start time for all activities) 
#' 
#' @keywords critical path, scheduling, project activities
#' 
#' @family scheduling
#' 
#' @examples
#'  
#' #ex.cpm is the list generated by the cpm() function:
#' # - est (Early Start Time)  - ex.cpm$est
#' # - eft (Early Finish Time) - ex.cpm$eft
#' # - lst (Late Start Time)   - ex.cpm$lst
#' # - lft (Late Finish Time)  - ex.cpm$lft
#'
#' ex.cpm.activities.schedule <- cpm.all.schedule(ex.cpm)
#'                                                
cpm.all.schedule <- cpm_all_schedule <- genAllCpmSched <- 
  function(cpm){
  est <- cpm$est
  slack <- (cpm$lst - cpm$est)
  
  # Constants
  slack1 <- slack + 1
  m <- prod(slack1)
  n <- length(slack)
  
  # Variables
  sched.list<-list(length=n)
  
  #Algorithm
  #1-generate est sequence for all activities
  for (i in 1:n){
    if (slack[i]==0){
      sched.list[i]<-est[i]
    }
    else{
      sched.list[[i]]<-seq(from=est[i],to=est[i]+slack[i])
    }
    
  }
 
  #2-generate the cartesian product of all ests
  all.sched<-expand.grid(sched.list) 
    
  return(as.matrix(all.sched[,1:n]))
}